name: maven verify

on:
  workflow_dispatch:
    inputs:
      build_branch:
        type: choice
        options: 
        - main
        - develop
        - feature

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from Git Repo
      uses: actions/checkout@v3
      with:
        ref: "${{ github.event.inputs.build_branch }}"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B verify